CREATE TABLE "OG_LA"."GAME_CHART_TASK" 
   (	"ID" NUMBER(15,0) NOT NULL ENABLE, 
	"GAME_ID" VARCHAR2(15), 
	"ISSUE" VARCHAR2(50), 
	"RESULT" VARCHAR2(4000), 
	"STATUS" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"RETRY_TIMES" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"RESULT_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";
  
  create  sequence GAME_CHART_TASK_ID_SEQ start with 1 increment by 1;
  
  ALTER TABLE OG_LA.GAME_CHART_TASK ADD CONSTRAINT GAME_CHART_TASK_PK PRIMARY KEY (ID);