
DROP TABLE GAME_CHART_TYPE;

CREATE TABLE GAME_CHART_TYPE(
ID             NUMBER(15,0) PRIMARY KEY,
NAME           VARCHAR2(50 CHAR) NOT NULL,
GAME_CLASS_ID  VARCHAR2(15 CHAR) NOT NULL,
CHART_CODE     VARCHAR2(50 CHAR) NOT NULL,
CREATE_DATE    DATE NOT NULL
);

CREATE SEQUENCE GAME_CHART_TYPE_ID_SEQ;


