CREATE TABLE OG_LA.GAME
(
  ID                    VARCHAR2(15 char)     PRIMARY KEY,
  NAME                  VARCHAR2(50 char),
  TYPE                  CHAR(4 char),
  GAME_CLASS_ID         VARCHAR2(15 char),
  IS_HOST               NUMBER  DEFAULT 0,
  CREATE_DATE           DATE
);

COMMENT ON TABLE OG_LA.GAME IS '彩票游戏';
COMMENT ON COLUMN OG_LA.GAME.ID IS '采种ID';
COMMENT ON COLUMN OG_LA.GAME.NAME IS '游戏名称';
COMMENT ON COLUMN OG_LA.GAME.TYPE IS '游戏类型:高频、境外';
COMMENT ON COLUMN OG_LA.GAME.GAME_CLASS_ID IS '游戏分类';
COMMENT ON COLUMN OG_LA.GAME.IS_HOST IS '热门采种:0否,1是';
COMMENT ON COLUMN OG_LA.GAME.CREATE_DATE IS '创建日期';